name: Test and Build

on:
  pull_request:
    branches:    
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  test:
    strategy:
      matrix:
        node-version: [17.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
    - name: Run tests
      run: yarn test